import type { PointValuation } from "./types";

const TPG_VALUATIONS_URL =
  "https://thepointsguy.com/loyalty-programs/monthly-valuations/";

/**
 * Manually maintained MVP estimates. These are local fallback data, not live
 * quotes. Update the value, source, and date together after a human review.
 */
export const POINT_VALUATIONS = [
  {
    id: "chase-ultimate-rewards",
    name: "Chase Ultimate Rewards",
    issuer: "Chase",
    kind: "bank",
    cpp: 2.05,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: true,
  },
  {
    id: "amex-membership-rewards",
    name: "American Express Membership Rewards",
    issuer: "American Express",
    kind: "bank",
    cpp: 2,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: true,
  },
  {
    id: "citi-thankyou-points",
    name: "Citi ThankYou Points",
    issuer: "Citi",
    kind: "bank",
    cpp: 1.85,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: true,
  },
  {
    id: "capital-one-miles",
    name: "Capital One Miles",
    issuer: "Capital One",
    kind: "bank",
    cpp: 1.85,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: true,
  },
  {
    id: "air-canada-aeroplan",
    name: "Air Canada Aeroplan",
    issuer: "Air Canada",
    kind: "airline",
    cpp: 1.5,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "british-airways-avios",
    name: "British Airways Club (Avios)",
    issuer: "British Airways",
    kind: "airline",
    cpp: 1.4,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "flying-blue",
    name: "Air France-KLM Flying Blue",
    issuer: "Air France-KLM",
    kind: "airline",
    cpp: 1.3,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "singapore-krisflyer",
    name: "Singapore Airlines KrisFlyer",
    issuer: "Singapore Airlines",
    kind: "airline",
    cpp: 1.35,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "virgin-atlantic-flying-club",
    name: "Virgin Atlantic Flying Club",
    issuer: "Virgin Atlantic",
    kind: "airline",
    cpp: 1.4,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "united-mileageplus",
    name: "United MileagePlus",
    issuer: "United Airlines",
    kind: "airline",
    cpp: 1.3,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "delta-skymiles",
    name: "Delta SkyMiles",
    issuer: "Delta Air Lines",
    kind: "airline",
    cpp: 1.2,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "american-aadvantage",
    name: "American Airlines AAdvantage",
    issuer: "American Airlines",
    kind: "airline",
    cpp: 1.4,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "southwest-rapid-rewards",
    name: "Southwest Rapid Rewards",
    issuer: "Southwest Airlines",
    kind: "airline",
    cpp: 1.4,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "jetblue-trueblue",
    name: "JetBlue TrueBlue",
    issuer: "JetBlue",
    kind: "airline",
    cpp: 1.25,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "world-of-hyatt",
    name: "World of Hyatt",
    issuer: "Hyatt",
    kind: "hotel",
    cpp: 1.7,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "marriott-bonvoy",
    name: "Marriott Bonvoy",
    issuer: "Marriott",
    kind: "hotel",
    cpp: 0.7,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "hilton-honors",
    name: "Hilton Honors",
    issuer: "Hilton",
    kind: "hotel",
    cpp: 0.6,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "ihg-one-rewards",
    name: "IHG One Rewards",
    issuer: "IHG",
    kind: "hotel",
    cpp: 0.5,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "choice-privileges",
    name: "Choice Privileges",
    issuer: "Choice Hotels",
    kind: "hotel",
    cpp: 0.6,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
  {
    id: "wyndham-rewards",
    name: "Wyndham Rewards",
    issuer: "Wyndham",
    kind: "hotel",
    cpp: 0.9,
    sourceName: "The Points Guy monthly valuations",
    sourceUrl: TPG_VALUATIONS_URL,
    updatedAt: "2026-07-18",
    transferable: false,
  },
] as const satisfies readonly PointValuation[];

export function getPointValuation(programId: string): PointValuation | undefined {
  return POINT_VALUATIONS.find((program) => program.id === programId);
}
